// packages/core/src/meta/index.ts
export { analyzeStructure } from './structural-analysis.js'
export type { RelationalAnalysis, RelationalTriple, TypedRole } from './structural-analysis.js'
export { clusterByStructure } from './clustering.js'
export type { EngramCluster } from './clustering.js'
export { alignCluster } from './alignment.js'
export type { AlignmentResult, MemberAlignment } from './alignment.js'
export { formulateMetaEngram } from './formulation.js'
export { validateMetaEngram } from './validation.js'
export type { ValidationResult } from './validation.js'
export { organizeHierarchy } from './hierarchy.js'
export { extractMetaEngrams } from './pipeline.js'
export type { ExtractionResult, ExtractOptions } from './pipeline.js'
export { isPlatitude, PLATITUDE_PATTERNS } from './platitudes.js'
export { tokenSimilarity } from './similarity.js'
