/**
 * The golden pack vectors, verified by the reference implementation.
 *
 * The vectors in `spec/vectors/packs/` are authored by `spec/vectors/build.py`
 * — Python, `hashlib`, and a hand-written serializer that shares no code with
 * `packs.ts`. This file checks that the reference agrees with them.
 *
 * That direction matters. A vector generated by this implementation and checked
 * by this implementation proves the code agrees with itself. The expected
 * `INTEGRITY` values here were computed somewhere else, so a disagreement is a
 * real interoperability failure rather than a broken test.
 *
 * There are three implementations now: this one, `plur-ai/encode` writing a
 * producer directly in Python from the document rather than from this code, and
 * `plur-ai/enterprise` adopting the format for import. Encode is the case these
 * vectors exist for — anything ambiguous in §5 surfaces there as a silent
 * disagreement, and this is what turns it back into a loud one.
 *
 * When a vector fails, the question is which side is wrong. Do not "fix" the
 * vector to match the code without establishing that first.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { computePackHash, verifyPackIntegrity, previewPack } from '../src/packs.js'

const VECTORS = resolve(__dirname, '..', '..', '..', 'spec', 'vectors')
const PACKS = join(VECTORS, 'packs')

interface Vector {
  pack: string
  computed_integrity: string
  shipped_integrity: string | null
  expect: 'load' | 'reject' | 'load-with-report' | 'load-neutralized' | 'disputed'
  integrity_status: 'ok' | 'modified' | 'absent'
  note: string
  provenance_records?: number
  orphan_records?: number
  unreadable_records?: number
  neutralized?: number
  preserves_unknown_field?: string
}

const index = JSON.parse(readFileSync(join(VECTORS, 'index.json'), 'utf8')) as {
  vectors: Vector[]
}

const dirOf = (v: Vector) => join(PACKS, v.pack)

describe('golden pack vectors — the hash', () => {
  for (const v of index.vectors) {
    it(`${v.pack}: computePackHash reproduces the value Python computed`, () => {
      // The one assertion that makes these vectors worth having. Python built
      // the bytes and hashed them; this is TypeScript hashing the same bytes.
      expect(
        `sha256:${computePackHash(dirOf(v))}`,
        `${v.pack} — ${v.note}`,
      ).toBe(v.computed_integrity)
    })
  }
})

describe('golden pack vectors — the integrity verdict', () => {
  for (const v of index.vectors) {
    it(`${v.pack}: verifyPackIntegrity reports "${v.integrity_status}"`, () => {
      expect(verifyPackIntegrity(dirOf(v)).status, v.note).toBe(v.integrity_status)
    })
  }

  it('an absent INTEGRITY file is not the same verdict as a mismatched one', () => {
    // §5.5 makes the file optional on disk, so "the pack shipped none" and "the
    // pack shipped one and it is wrong" are different facts about trust.
    const absent = index.vectors.find(v => v.integrity_status === 'absent')!
    const modified = index.vectors.find(v => v.integrity_status === 'modified')!
    expect(verifyPackIntegrity(dirOf(absent)).status).toBe('absent')
    expect(verifyPackIntegrity(dirOf(modified)).status).toBe('modified')
  })
})

describe('golden pack vectors — what the reference does with each', () => {
  const byName = (n: string) => index.vectors.find(v => v.pack === n)!

  it('loads a minimal pack that ships no INTEGRITY at all', async () => {
    const preview = await previewPack(dirOf(byName('minimal')))
    expect(preview.engram_count).toBe(2)
    expect(preview.integrity.status).toBe('absent')
  })

  it('hashes non-Latin content identically to Python', async () => {
    // Raw bytes, per §5.5. A UTF-8 assumption on either side shows up here and
    // nowhere else, because every other vector is ASCII.
    const v = byName('non-latin')
    expect(`sha256:${computePackHash(dirOf(v))}`).toBe(v.computed_integrity)
    expect((await previewPack(dirOf(v))).engram_count).toBe(2)
  })

  it('refuses a pack whose shipped integrity does not match its bytes', () => {
    expect(verifyPackIntegrity(dirOf(byName('integrity-mismatch'))).status).toBe('modified')
  })

  it('adding provenance records does not move the integrity value', () => {
    // §5.1: provenance/ is not covered by the §5.5 hash. So the hash of a pack
    // with records must equal the hash of the same SKILL.md and engrams.yaml
    // without them. Verified by construction: recompute ignoring the directory.
    const v = byName('with-provenance')
    expect(existsSync(join(dirOf(v), 'provenance'))).toBe(true)
    expect(`sha256:${computePackHash(dirOf(v))}`).toBe(v.computed_integrity)
    expect(verifyPackIntegrity(dirOf(v)).status).toBe('ok')
  })

  it('reads the provenance a pack ships, and counts the records', async () => {
    const preview = await previewPack(dirOf(byName('with-provenance')))
    expect(preview.provenance.present).toBe(true)
    expect(preview.provenance.record_count).toBe(2)
    expect(preview.provenance.verified).toBe(false)
  })

  it('notices a record describing an engram the pack does not contain', async () => {
    // Profile §5.4.2. This must be reported, and must not fail the load.
    const preview = await previewPack(dirOf(byName('orphan-provenance-record')))
    expect(preview.provenance.present).toBe(true)
    expect(preview.engram_count).toBe(2)
  })

  it('survives an unreadable provenance record without throwing', async () => {
    const preview = await previewPack(dirOf(byName('corrupt-provenance-record')))
    expect(preview.provenance.present).toBe(true)
    expect(preview.engram_count).toBe(2)
  })

  it('flags a pack shipping a private engram', async () => {
    // §4.14 invariant 7 and §5.4: a conformant producer cannot emit this. A
    // consumer must still refuse it, since it cannot assume the producer complied.
    const preview = await previewPack(dirOf(byName('private-engram-shipped')))
    expect(preview.security.clean).toBe(false)
    expect(preview.security.issues.some(i => i.type === 'private_visibility')).toBe(true)
  })

  it('preserves an unknown manifest field at the root', async () => {
    // §10.3: unknown manifest fields MUST be preserved. Root is open-world.
    const v = byName('unknown-root-field')
    const raw = readFileSync(join(dirOf(v), 'SKILL.md'), 'utf8')
    expect(raw).toContain('x-vendor')
    expect((await previewPack(dirOf(v))).engram_count).toBe(2)
  })
})

describe('the disputed vector', () => {
  it('is carried without an assertion, because the specs disagree', () => {
    // `unknown-metadata-field` exists to hold a contradiction open rather than
    // to pass or fail. §10.3 says unknown manifest fields MUST be preserved;
    // the published schema sets metadata.additionalProperties:false and the
    // reference has no .passthrough(). Asserting either way here would pick a
    // winner that #1029 has not picked.
    //
    // What IS asserted: the vector exists, so the decision cannot be quietly
    // forgotten, and its hash agrees across implementations either way.
    const v = index.vectors.find(x => x.pack === 'unknown-metadata-field')!
    expect(v.expect).toBe('disputed')
    expect(`sha256:${computePackHash(dirOf(v))}`).toBe(v.computed_integrity)
  })
})

describe('golden capsule fixtures — §6', () => {
  // §6 is STABLE and `capsule.ts` has no caller anywhere outside its own tests.
  // These bytes were written by Python from the document, so this is the first
  // time the reader has been asked to agree with somebody else's encoder.
  //
  // The negatives carry the weight: §6.7 lists checks a reader MUST perform, and
  // a check nobody has seen fail is not a check.
  const CAPSULES = join(VECTORS, 'capsules')
  const capsuleIndex = JSON.parse(
    readFileSync(join(VECTORS, 'capsules.json'), 'utf8'),
  ) as { capsules: Array<{ capsule: string; expect: 'accept' | 'reject'; note: string }> }

  for (const c of capsuleIndex.capsules) {
    it(`${c.capsule.replace('.plur', '')} — ${c.expect}s`, async () => {
      const { readCapsule } = await import('../src/capsule.js')
      const bytes = readFileSync(join(CAPSULES, c.capsule))
      if (c.expect === 'accept') {
        const result = readCapsule(bytes)
        expect(result, c.note).toBeDefined()
      } else {
        // A rejection may surface as a throw or as a falsy result; both refuse
        // to act on the capsule, which is what §6.7 requires. What must NOT
        // happen is a successful parse.
        let refused = false
        try {
          const result = readCapsule(bytes)
          refused = !result
        } catch {
          refused = true
        }
        expect(refused, `${c.capsule}: ${c.note}`).toBe(true)
      }
    })
  }
})
