#!/usr/bin/env python3
"""Build the golden pack vectors.

Read this before changing anything here.

**These vectors are authored in Python and verified in TypeScript, on purpose.**
A vector generated by the reference implementation and then checked by the
reference implementation proves only that the code agrees with itself. Building
them here, with `hashlib` and a hand-written serializer, means the expected
`INTEGRITY` values come from somewhere that shares no code with `packs.ts`.

That is the whole point. `spec/README.md` names conformance vectors as the
cheapest thing that unlocks the standard, and there are now three implementations
to keep honest:

  core         TypeScript, the reference
  encode       Python, writing a producer directly from the document (encode#32)
  enterprise   adopting the format for import (enterprise#1050)

Encode reads the specification and not our TypeScript. Any ambiguity in §5
surfaces there as a silent disagreement rather than a compile error, and these
vectors are what turn it back into a loud one.

**The bytes are the artifact.** Vectors are committed, not generated at test
time. This script exists to record how they were made and to rebuild them when a
rule changes deliberately — never as a step in the test run. If a vector's hash
changes because the code changed, that is the vector doing its job.

**Every vector declares an outcome, and the outcome is asserted.** `index.json`
says what a consumer must DO with each pack — load it, refuse it, load it and
report something, load it and neutralize something — with the counts a consumer
must report. `packages/core/test/spec-vectors.test.ts` installs every vector
through the reference and checks those declarations; `verify.py --index` checks
them against the fixture bytes from outside. A vector whose declaration is not
asserted certifies nothing, which was the state of five of the first eleven.

Usage:
    python3 build.py            # rebuild every vector into ./packs/ and index.json
    python3 build.py --check    # rebuild into a temp dir and diff; exit 1 on drift
"""
from __future__ import annotations

import argparse
import filecmp
import hashlib
import json
import shutil
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).parent
PACKS = HERE / "packs"
INDEX = HERE / "index.json"


# --- serialization -----------------------------------------------------------
#
# Hand-written rather than pyyaml, for two reasons. The bytes have to be exactly
# what we intend, since §5.5 hashes raw file bytes and forbids re-serializing
# before hashing. And a vector whose content depends on a YAML library's emitter
# settings is a vector that changes when that library does.
#
# `ensure_ascii=False` everywhere a value is emitted. `json.dumps` escapes
# anything outside ASCII by default, so the first `non-latin` vector was pure
# ASCII — `デ...` — and caught no encoding assumption at all. A vector that
# claims to pin raw-byte hashing of UTF-8 must contain bytes above 0x7f.


def engram_yaml(engrams: list[dict]) -> str:
    """Emit a §2.1 store document. Deliberately minimal and explicit."""
    out = ["engrams:"]
    for e in engrams:
        first = True
        for key, value in e.items():
            prefix = "  - " if first else "    "
            first = False
            if isinstance(value, bool):
                rendered = "true" if value else "false"
            elif isinstance(value, (int, float)):
                rendered = str(value)
            elif isinstance(value, list):
                rendered = "[" + ", ".join(json.dumps(str(v), ensure_ascii=False) for v in value) + "]"
            elif isinstance(value, dict):
                inner = ", ".join(f"{k}: {json.dumps(v, ensure_ascii=False)}" for k, v in value.items())
                rendered = "{" + inner + "}"
            else:
                rendered = json.dumps(str(value), ensure_ascii=False)
            out.append(f"{prefix}{key}: {rendered}")
    return "\n".join(out) + "\n"


def skill_md(manifest: dict, prose: str) -> str:
    """Emit SKILL.md: the manifest as YAML frontmatter, then prose (§5.1)."""
    lines = ["---"]

    def emit(obj: dict, indent: str) -> None:
        for key, value in obj.items():
            if isinstance(value, dict):
                lines.append(f"{indent}{key}:")
                emit(value, indent + "  ")
            elif isinstance(value, list):
                rendered = "[" + ", ".join(str(v) for v in value) + "]"
                lines.append(f"{indent}{key}: {rendered}")
            elif isinstance(value, bool):
                lines.append(f"{indent}{key}: {'true' if value else 'false'}")
            elif isinstance(value, int):
                lines.append(f"{indent}{key}: {value}")
            else:
                lines.append(f'{indent}{key}: "{value}"')

    emit(manifest, "")
    lines += ["---", "", prose, ""]
    return "\n".join(lines)


def pack_integrity(skill_bytes: bytes, engram_bytes: bytes) -> str:
    """§5.5: SHA-256 over bytes(SKILL.md) followed by bytes(engrams.yaml)."""
    return "sha256:" + hashlib.sha256(skill_bytes + engram_bytes).hexdigest()


# --- vector content ----------------------------------------------------------

BASE_ENGRAMS = [
    {
        "id": "ENG-PACK-VEC-001",
        "statement": "Deploys wait for migrations, never the other way round",
        "type": "behavioral",
        "status": "active",
        "scope": "global",
        "visibility": "public",
        "domain": "ops.deployment",
    },
    {
        "id": "ENG-PACK-VEC-002",
        "statement": "Connection pools cap at 100 on the shared tier",
        "type": "architectural",
        "status": "active",
        "scope": "global",
        "visibility": "public",
        "domain": "ops.capacity",
    },
]


def without(engram: dict, *keys: str) -> dict:
    """A copy of an engram with the named keys absent — not null, absent."""
    return {k: v for k, v in engram.items() if k not in keys}


def base_manifest(name: str, **extra) -> dict:
    manifest = {
        "name": name,
        "version": "1.0.0",
        "description": "A conformance vector.",
        "creator": "local:spec",
        "license": "cc-by-4.0",
        "tags": ["conformance", "vector"],
        "metadata": {
            "injection_policy": "on_match",
            "match_terms": ["deploy", "migration", "pool"],
            "engram_count": 2,
        },
    }
    manifest.update(extra)
    return manifest


def with_provenance(name: str) -> dict:
    return base_manifest(name, metadata={
        "injection_policy": "on_match",
        "match_terms": ["deploy", "migration", "pool"],
        "engram_count": 2,
        "provenance": True,
    })


def write_pack(
    slug: str,
    manifest: dict,
    engrams: list[dict],
    *,
    integrity: str | None | bool = True,
    prose: str = "Prose for humans goes here.",
    manifest_filename: str = "SKILL.md",
    extra_files: dict[str, str] | None = None,
    root: Path | None = None,
) -> dict:
    """Write one vector. Returns its index entry.

    `integrity=True` writes the correct value, a string writes that value
    verbatim (for negative cases), and None writes no INTEGRITY file at all.
    """
    root = root or PACKS
    d = root / slug
    if d.exists():
        shutil.rmtree(d)
    d.mkdir(parents=True)

    engram_text = engram_yaml(engrams)
    engram_bytes = engram_text.encode("utf-8")

    if manifest_filename == "SKILL.md":
        manifest_text = skill_md(manifest, prose)
    else:
        # The deprecated standalone manifest.yaml (§5.1). It does NOT contribute
        # to the hash, so the hashed SKILL.md is absent for this vector.
        manifest_text = skill_md(manifest, prose).split("---")[1].strip() + "\n"
    manifest_bytes = manifest_text.encode("utf-8")

    (d / manifest_filename).write_bytes(manifest_bytes)
    (d / "engrams.yaml").write_bytes(engram_bytes)

    # §5.5 hashes SKILL.md ‖ engrams.yaml. A pack shipping only manifest.yaml
    # has no SKILL.md byte contribution, which is exactly what the spec says.
    hashed_manifest = manifest_bytes if manifest_filename == "SKILL.md" else b""
    correct = pack_integrity(hashed_manifest, engram_bytes)

    if integrity is True:
        (d / "INTEGRITY").write_text(correct + "\n")
        shipped = correct
    elif integrity is None:
        shipped = None
    else:
        (d / "INTEGRITY").write_text(str(integrity) + "\n")
        shipped = str(integrity)

    for rel, content in (extra_files or {}).items():
        target = d / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content.encode("utf-8"))

    return {
        "pack": slug,
        "engram_count": len(engrams),
        "computed_integrity": correct,
        "shipped_integrity": shipped,
    }


def provenance_record(engram_id: str, pack: str) -> str:
    """A minimal portable per-engram record (profile §5.3.5)."""
    return json.dumps(
        {
            "@context": {
                "prov": "http://www.w3.org/ns/prov#",
                "engram": "https://plur.ai/ns/engram#",
                "odrl": "http://www.w3.org/ns/odrl/2/",
                "xsd": "http://www.w3.org/2001/XMLSchema#",
            },
            "@graph": [
                {
                    "@id": f"engram:record/{engram_id}",
                    "@type": ["prov:Bundle", "prov:Entity"],
                    "engram:describes": {"@id": f"engram:{engram_id}"},
                    "engram:recordIsSelfContained": True,
                    "engram:historyEvents": 0,
                },
                {
                    "@id": f"engram:{engram_id}",
                    "@type": ["prov:Entity", "engram:Engram"],
                    "engram:license": "cc-by-4.0",
                    "engram:licenseSource": "inheritedFromPack",
                    "engram:memberOf": {"@id": f"engram:pack/{pack}@1.0.0"},
                },
            ],
        },
        indent=2,
    ) + "\n"


def build(root: Path) -> list[dict]:
    """Every vector, in the order they appear in index.json.

    Index fields beyond the hash, all asserted by the TypeScript side and
    checked against the fixture by `verify.py --index`:

      expect              load | reject | load-with-report | load-neutralized | disputed
      integrity_status    ok | modified | absent          (§5.5, §5.6.1 step 1)
      provenance_records  readable records for shipped engrams (profile §5.4.2)
      orphan_records      records naming an engram the pack does not ship
      unreadable_records  records that cannot be read
      held_private        engrams with no `visibility`, held private, reported (§5.6.1 step 2)
      neutralized         {"pinned": n, "locked": n} — counts a consumer MUST report (§5.6.5)
      preserves_unknown_field  a root manifest key that MUST survive (§10.3 rule 2)
    """
    vectors: list[dict] = []

    def add(entry: dict, **meta) -> None:
        entry.update(meta)
        vectors.append(entry)

    # ---- positive ----------------------------------------------------------

    add(
        write_pack("minimal", base_manifest("minimal"), BASE_ENGRAMS,
                   integrity=None, root=root),
        expect="load",
        integrity_status="absent",
        note="SKILL.md + engrams.yaml only. §5.1 makes INTEGRITY optional on disk; "
             "§5.6.1 step 1 makes its absence a third verdict, not a pass.",
    )

    add(
        write_pack("with-integrity", base_manifest("with-integrity"), BASE_ENGRAMS,
                   root=root),
        expect="load",
        integrity_status="ok",
        note="The ordinary case. Recomputing over raw bytes must reproduce the shipped value (§5.5).",
    )

    add(
        write_pack(
            "with-provenance",
            with_provenance("with-provenance"),
            BASE_ENGRAMS,
            extra_files={
                "provenance/ENG-PACK-VEC-001.jsonld": provenance_record("ENG-PACK-VEC-001", "with-provenance"),
                "provenance/ENG-PACK-VEC-002.jsonld": provenance_record("ENG-PACK-VEC-002", "with-provenance"),
            },
            root=root,
        ),
        expect="load",
        integrity_status="ok",
        provenance_records=2,
        note="§5.1: provenance/ is OPTIONAL and NOT covered by the hash. "
             "The INTEGRITY value must equal the with-integrity pack's construction, "
             "i.e. adding records must not move it. Profile §5.4.1: the records survive the install.",
    )

    add(
        write_pack("non-latin", base_manifest("non-latin"), [
            {**BASE_ENGRAMS[0], "statement": "デプロイは移行の後に実行する"},
            {**BASE_ENGRAMS[1], "statement": "Пул соединений ограничен 100"},
        ], root=root),
        expect="load",
        integrity_status="ok",
        note="§5.5 hashes raw bytes, so UTF-8 content must hash identically in both "
             "implementations. The fixture carries bytes above 0x7f — the test checks "
             "that it does — so a latin1 or ASCII assumption on either side fails here.",
    )

    add(
        write_pack("unknown-root-field",
                   base_manifest("unknown-root-field", **{"x-vendor": "something-we-do-not-know"}),
                   BASE_ENGRAMS, root=root),
        expect="load",
        integrity_status="ok",
        preserves_unknown_field="x-vendor",
        note="§10.3 rule 2: unknown manifest fields MUST be preserved. Root is "
             "additionalProperties:true, so the parsed manifest must still carry it.",
    )

    # ---- the contradiction, encoded rather than argued about ---------------

    add(
        write_pack("unknown-metadata-field",
                   base_manifest("unknown-metadata-field", metadata={
                       "injection_policy": "on_match",
                       "match_terms": ["deploy"],
                       "engram_count": 2,
                       "x-vendor-hint": "something-we-do-not-know",
                   }),
                   BASE_ENGRAMS, root=root),
        expect="disputed",
        integrity_status="ok",
        note="§10.3 rule 2 says unknown manifest fields MUST be preserved; the published "
             "schema sets metadata.additionalProperties:false and the reference has "
             "no .passthrough() there. The two disagree, so this vector asserts nothing "
             "beyond its hash until #1029 decides. It exists so the decision cannot be forgotten.",
    )

    # ---- load, and report --------------------------------------------------

    add(
        write_pack(
            "orphan-provenance-record",
            with_provenance("orphan-provenance-record"),
            BASE_ENGRAMS,
            extra_files={
                "provenance/ENG-PACK-VEC-001.jsonld": provenance_record("ENG-PACK-VEC-001", "orphan-provenance-record"),
                "provenance/ENG-PACK-VEC-999.jsonld": provenance_record("ENG-PACK-VEC-999", "orphan-provenance-record"),
            },
            root=root,
        ),
        expect="load-with-report",
        integrity_status="ok",
        provenance_records=1,
        orphan_records=1,
        note="Profile §5.4.2: a record describing an engram the pack does not "
             "contain MUST be reported. It does not fail the install.",
    )

    add(
        write_pack(
            "corrupt-provenance-record",
            with_provenance("corrupt-provenance-record"),
            BASE_ENGRAMS,
            extra_files={"provenance/ENG-PACK-VEC-001.jsonld": "{ this is not json\n"},
            root=root,
        ),
        expect="load-with-report",
        integrity_status="ok",
        provenance_records=0,
        unreadable_records=1,
        note="Profile §5.4.2: unreadable records MUST be counted and reported, "
             "never silently skipped, and MUST NOT abort the install. A tester's corrupt "
             "record installed with exit 0 and no output.",
    )

    add(
        write_pack("omitted-visibility", base_manifest("omitted-visibility"),
                   [BASE_ENGRAMS[0], without(BASE_ENGRAMS[1], "visibility")],
                   root=root),
        expect="load-with-report",
        integrity_status="ok",
        held_private=1,
        note="§5.6.1 step 2: an engram with NO visibility field takes the §4.4 default "
             "on the consumer's side. That is the consumer's assignment, not the "
             "producer's declaration, so the pack loads; the engram is held as private "
             "and reported, and MUST NOT be re-exported (§5.4).",
    )

    # ---- load, and neutralize ----------------------------------------------

    add(
        write_pack("pinned-engram-shipped", base_manifest("pinned-engram-shipped"),
                   [BASE_ENGRAMS[0], {**BASE_ENGRAMS[1], "pinned": True}],
                   root=root),
        expect="load-neutralized",
        integrity_status="ok",
        neutralized={"pinned": 1, "locked": 0},
        note="§5.4 makes stripping `pinned` a consumer MUST, and §5.6.1 step 3 requires "
             "the count be reported per field (§5.6.5). The pack loads; the flag does not survive.",
    )

    add(
        write_pack("locked-engram-shipped", base_manifest("locked-engram-shipped"),
                   [BASE_ENGRAMS[0], {**BASE_ENGRAMS[1], "commitment": "locked",
                                      "locked_at": "2026-01-01T00:00:00Z", "locked_reason": "the producer wanted this permanent"}],
                   root=root),
        expect="load-neutralized",
        integrity_status="ok",
        neutralized={"pinned": 0, "locked": 1},
        note="§5.4 makes downgrading `commitment: locked` to `decided` a consumer MUST, "
             "with `locked_at` and `locked_reason` removed, and §5.6.5 requires the count "
             "per field — a pack whose only host-overriding field is a locked commitment "
             "must not be altered in silence. The pack loads; the lock does not survive.",
    )

    # ---- refuse ------------------------------------------------------------

    add(
        write_pack("integrity-mismatch", base_manifest("integrity-mismatch"), BASE_ENGRAMS,
                   integrity="sha256:" + "0" * 64, root=root),
        expect="reject",
        integrity_status="modified",
        note="§5.5: a receiver MUST treat a mismatch as a failed integrity check; "
             "§5.6.1 step 1: the install MUST abort unless the installer explicitly "
             "overrides it for this pack.",
    )

    add(
        write_pack("private-engram-shipped", base_manifest("private-engram-shipped"),
                   [BASE_ENGRAMS[0], {**BASE_ENGRAMS[1], "visibility": "private"}],
                   root=root),
        expect="reject",
        integrity_status="ok",
        note="§5.4 and §4.14 invariant 7: a private engram MUST NOT be in a pack, so a "
             "conformant producer cannot emit this. §5.6.1 step 2: a consumer MUST refuse "
             "a pack that DECLARES `visibility: private`, and there is no override.",
    )

    return vectors


def index_document(vectors: list[dict]) -> str:
    return json.dumps(
        {
            "note": "Golden pack vectors. Authored in Python, verified in TypeScript "
                    "and Python, so neither implementation grades its own work. Every "
                    "`expect` and every count is asserted on both sides. See build.py "
                    "for the fields, and README.md for how to run them.",
            "standard": "ENGRAM-STANDARD-v1.md",
            "vectors": vectors,
        }, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="rebuild into a temp dir and fail on any difference, index.json included")
    args = ap.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            fresh = Path(tmp) / "packs"
            fresh.mkdir()
            vectors = build(fresh)
            drift = []
            for path in sorted(fresh.rglob("*")):
                if path.is_dir():
                    continue
                rel = path.relative_to(fresh)
                committed = PACKS / rel
                if not committed.exists():
                    drift.append(f"missing from the repository: packs/{rel}")
                elif not filecmp.cmp(path, committed, shallow=False):
                    drift.append(f"differs from the repository: packs/{rel}")
            for path in sorted(PACKS.rglob("*")):
                if path.is_file() and not (fresh / path.relative_to(PACKS)).exists():
                    drift.append(f"in the repository but not rebuilt: packs/{path.relative_to(PACKS)}")
            # The declarations are part of the artifact. An `expect` edited by
            # hand to make a test pass is the same failure as an edited byte.
            if not INDEX.exists():
                drift.append("missing from the repository: index.json")
            elif INDEX.read_text(encoding="utf-8") != index_document(vectors):
                drift.append("differs from the repository: index.json")
            if drift:
                print("Vector drift:", file=sys.stderr)
                for d in drift:
                    print(f"  {d}", file=sys.stderr)
                print("\nRun `python3 build.py` if the change was intended.", file=sys.stderr)
                return 1
            print("Vectors and index.json match what this script builds.")
            return 0

    PACKS.mkdir(exist_ok=True)
    vectors = build(PACKS)
    INDEX.write_text(index_document(vectors), encoding="utf-8")
    print(f"Built {len(vectors)} vectors into {PACKS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
