import { readSync, mkdirSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { tmpdir } from 'os'
import { cursorContextRulePath } from '../mcp-config.js'

/**
 * Shared stdin-reading and sentinel-path helpers for the four hook-cursor-*
 * commands. Split out from any single hook file because all four need the
 * exact same conversation-id resolution and directory layout.
 */

export function readStdinJson(): Record<string, unknown> {
  try {
    const chunks: Buffer[] = []
    const buf = Buffer.alloc(65536)
    while (true) {
      try {
        const n = readSync(0, buf, 0, buf.length, null)
        if (n === 0) break
        chunks.push(Buffer.from(buf.subarray(0, n)))
      } catch {
        break
      }
    }
    const raw = Buffer.concat(chunks).toString('utf8').trim()
    return raw ? JSON.parse(raw) : {}
  } catch {
    return {}
  }
}

/**
 * Cursor's hook payload envelope is not fully pinned down across doc sources
 * as of 2026-07 (the hooks API is explicitly beta): some examples show
 * `conversation_id` as the per-chat identifier, a structured summary of the
 * same docs page showed `session_id`. Accept either so these hooks work
 * regardless of which one Cursor actually sends — Task 11 (manual
 * verification against real Cursor) confirms which is real; narrow this
 * fallback then if only one shows up in practice.
 */
export function cursorConversationId(input: Record<string, unknown>): string {
  return String(input.conversation_id ?? input.session_id ?? '')
}

/**
 * Is this tool call `plur_session_start`? Hoisted here (audit fix) because
 * the original draft of this plan implemented this check twice, differently,
 * in hook-cursor-guard.ts (an exact-match Set) and hook-cursor-post-tool.ts
 * (an endsWith check) — a real divergence risk if Task 11's manual
 * verification finds the real tool-name format needs adjusting: fixing one
 * copy and missing the other would leave the guard and the post-tool
 * sentinel-writer permanently disagreeing about whether a session started.
 * One implementation, used by both.
 */
export function isPlurSessionStartTool(toolName: string): boolean {
  return toolName === 'plur_session_start' || toolName.endsWith('__plur_session_start')
}

export function sessionsDir(): string {
  const dir = join(tmpdir(), 'plur-cursor-sessions')
  mkdirSync(dir, { recursive: true })
  return dir
}

export function sentinelPath(conversationId: string): string {
  return join(sessionsDir(), `${conversationId}.marker`)
}

export function lastReminderPath(conversationId: string): string {
  return join(sessionsDir(), `${conversationId}.reminded`)
}

export function stopCountPath(conversationId: string): string {
  return join(sessionsDir(), `${conversationId}.stopcount`)
}

/**
 * Mark a conversation as started: write both the guard's sentinel and reset
 * the reminder timer in one call. Three call sites need this (session-start
 * hook on the normal interactive path; post-tool hook on the explicit
 * plur_session_start path; and the guard's own deadlock-prevention fallback,
 * audit fix — see hook-cursor-guard.ts) and all three must do exactly the
 * same two writes, so it's one function instead of copy-pasted pairs.
 */
export function markSessionStarted(conversationId: string): void {
  const now = String(Date.now())
  writeFileSync(sentinelPath(conversationId), now)
  writeFileSync(lastReminderPath(conversationId), now)
}

/**
 * Write recalled engram content to the dynamic context rule file (audit fix,
 * live-evidence version — see Global Constraints). Cursor's own team
 * confirmed on their forum that `additional_context` from BOTH `sessionStart`
 * and `postToolUse` is dropped by a race condition ("runs async before the
 * composer handle is fully created") — a filed, acknowledged bug with no fix
 * timeline as of this plan's writing. The community-and-team-confirmed
 * workaround is to write the same content into a `.cursor/rules/*.mdc` file
 * instead: Cursor's rules engine reliably loads `alwaysApply: true` rules,
 * unlike the broken hook-output channel. This is now the PRIMARY delivery
 * mechanism for hook-cursor-session-start.ts and hook-cursor-post-tool.ts —
 * not a fallback — both also still emit `additional_context` too (harmless,
 * and picks up automatically if/when Cursor fixes the underlying bug).
 */
export function writeContextRule(content: string): void {
  const path = cursorContextRulePath()
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(
    path,
    '---\n' +
    'description: PLUR recalled memory for this session (auto-generated by plur hooks — do not edit by hand, changes are overwritten)\n' +
    'alwaysApply: true\n' +
    '---\n\n' +
    `${content}\n`,
  )
}
