import {
  accessSync, chmodSync, chownSync, closeSync, constants, copyFileSync, existsSync, fsyncSync, lstatSync,
  openSync, readFileSync, readdirSync, readlinkSync, realpathSync, renameSync, statSync, unlinkSync,
  writeFileSync,
} from 'fs'
import { randomBytes } from 'crypto'
import { basename, dirname, join } from 'path'

/**
 * Put PLUR's instruction section into a file the user also writes in
 * (CLAUDE.md, AGENTS.md, Claw's SYSTEM.md), upgrading an older one.
 *
 * The one rule: text PLUR did not write is never removed (#1520 audit B1).
 * Before v4 the sections carried no end marker, so where an old section ends
 * cannot be read off the file. Instead an old section counts as PLUR's only
 * when its lines are exactly a text PLUR shipped (the `shipped` list,
 * generated by scripts/extract-plur-section-history.mjs). Only trailing
 * whitespace and line endings may differ; a change of indentation or of
 * blank lines counts as the user's edit.
 * Such a section is replaced; any other section under the same heading is
 * left exactly as it is, the new section is added beside it, and the result
 * reports it in `keptSections` so the caller can tell the user.
 *
 * Markdown is read with fenced code blocks and HTML comment blocks in mind
 * (S1): a heading or marker inside one is example or hidden text, not
 * structure, and a file that ends inside one has it closed before anything is
 * appended, so the next run still sees the section (R1). A byte-order mark is
 * kept (N2), every PLUR section in the file is handled, not just the first
 * (N1), only a marker on a line of its own counts as an installed section
 * (N3), and a CRLF file stays CRLF (N4).
 */

export interface InstructionSectionOptions {
  /** The section to install: starts with the heading line, ends with the marker line. */
  section: string
  /** The heading line that opens a PLUR section, e.g. `## PLUR Memory`. Matched as a whole line. */
  heading: string
  /** The current version marker, e.g. `<!-- plur-instructions-v4 -->`. */
  marker: string
  /** Section texts PLUR has shipped before. Only these are ever replaced. */
  shipped: readonly string[]
  /** First line of a newly created file (e.g. `# CLAUDE.md`). Omitted: the file is just the section. */
  title?: string
}

export interface InstructionSectionResult {
  content: string
  /**
   * created: there was no file. added: the section was appended.
   * upgraded: a shipped section was replaced (and any other shipped copies
   * removed). already: a current section is present and nothing else changed.
   */
  status: 'created' | 'added' | 'upgraded' | 'already' | 'skipped'
  /** Sections under the PLUR heading that PLUR did not write, left untouched. */
  keptSections: number
  /** The file ended inside a code fence or HTML comment, which was closed before the section was appended. */
  closedOpenBlock?: 'fence' | 'comment'
  /** With status `skipped`: why nothing was written. */
  skipReason?: string
}

const BOM = '﻿'

/** The text a line holds, without a trailing CR. */
const bare = (line: string) => line.endsWith('\r') ? line.slice(0, -1) : line

/**
 * What a file still has open at its end, if anything. `unsure`: a code block
 * may or may not still be open, depending on Markdown structure PLUR cannot
 * see, so nothing is appended (#1520 third re-audit N1).
 */
type OpenBlock =
  | { kind: 'fence'; close: string }
  | { kind: 'comment'; close: string }
  | { kind: 'unsure' }
  | null

const indentOf = (line: string) => /^ */.exec(line)![0].length
const LIST_MARKER = /^( *)([-*+]|\d{1,9}[.)])( {1,4})\S/

/**
 * The content column of the list item a fence at `indent` (line `at`) sits
 * in, or null when it is not inside one. Walks back over the item's earlier
 * lines (blank, or indented at least as far as the fence) to its marker line;
 * the fence belongs to that item when it starts within the item's content
 * (column c to c+3).
 */
function listContainer(lines: string[], hidden: boolean[], at: number, indent: number): number | null {
  for (let j = at - 1; j >= 0; j--) {
    const line = bare(lines[j])
    if (line.trim() === '') continue
    if (hidden[j]) return null
    const m = LIST_MARKER.exec(line)
    if (m) {
      const c = m[1].length + m[2].length + m[3].length
      if (indent >= c && indent <= c + 3) return c
      if (indentOf(line) < indent) return null
      continue
    }
    if (indentOf(line) < indent) return null
  }
  return null
}

/**
 * Lines that are not markdown structure: lines of a fenced code block (fence
 * lines included, CommonMark ``` and ~~~) and lines of an HTML comment block
 * (a line starting with `<!--`, through the line holding `-->`). A heading
 * or marker on such a line is example or hidden text, never a section
 * (#1520 audit S1, re-audit low b). Also reports a block still open at the
 * end of the file (re-audit R1).
 *
 * A fence inside a list item ends where the item ends — at the first
 * non-blank line indented less than the item's content — as CommonMark has
 * it, so a later paragraph or list item is not taken for code, and closing
 * the fence at the end of the file never opens a new block (third re-audit
 * N1). A fence indented 1-3 spaces outside any list item PLUR can see is
 * treated as top level; if a less-indented line follows it, PLUR cannot be
 * sure the block is still open and reports `unsure`.
 */
function hiddenLines(lines: string[]): { hidden: boolean[]; openAtEnd: OpenBlock } {
  const hidden: boolean[] = new Array(lines.length).fill(false)
  let fence: { char: string; len: number; indent: number; container: number | null; doubtful: boolean } | null = null
  let comment = false
  for (let i = 0; i < lines.length; i++) {
    const line = bare(lines[i])
    if (fence) {
      const blank = line.trim() === ''
      if (fence.container !== null && !blank && indentOf(line) < fence.container) {
        fence = null // the list item ended, and its code block with it
      } else {
        hidden[i] = true
        const base = fence.container ?? 0
        const m = /^( *)(`{3,}|~{3,})[ \t]*$/.exec(line)
        if (m && m[1].length - base >= 0 && m[1].length - base <= 3 && m[2][0] === fence.char && m[2].length >= fence.len) {
          fence = null
        } else if (fence.container === null && fence.indent > 0 && !blank && indentOf(line) < fence.indent) {
          fence.doubtful = true
        }
        continue
      }
    }
    if (comment) {
      hidden[i] = true
      if (line.includes('-->')) comment = false
      continue
    }
    const m = /^( *)(`{3,}|~{3,})(.*)$/.exec(line)
    if (m && !(m[2][0] === '`' && m[3].includes('`'))) {
      const indent = m[1].length
      const container = listContainer(lines, hidden, i, indent)
      if (indent <= 3 || container !== null) {
        hidden[i] = true
        fence = { char: m[2][0], len: m[2].length, indent, container, doubtful: false }
        continue
      }
    }
    const c = /^ {0,3}<!--/.exec(line)
    if (c && !line.slice(c[0].length).includes('-->')) {
      hidden[i] = true
      comment = true
    }
  }
  let openAtEnd: OpenBlock = null
  if (fence) {
    // The close carries the opening fence's indentation, so a fence in a list
    // item is closed inside that item (#1520 second re-audit L1).
    openAtEnd = fence.doubtful
      ? { kind: 'unsure' }
      : { kind: 'fence', close: ' '.repeat(fence.indent) + fence.char.repeat(fence.len) }
  } else if (comment) {
    openAtEnd = { kind: 'comment', close: '-->' }
  }
  return { hidden, openAtEnd }
}

/** A line as compared: trailing whitespace and CR are not an edit; anything else is. */
const cmp = (line: string) => bare(line).replace(/[ \t]+$/, '')
/** A line's content with surrounding whitespace removed, used only to spot headings, markers and blank lines. */
const norm = (line: string) => bare(line).trim()

/**
 * The lines of a text as compared: BOM dropped, leading and trailing blank
 * lines dropped, trailing whitespace dropped. Leading indentation and blank
 * lines inside are kept, so changing them is an edit (#1520 re-audit low a).
 */
function comparable(text: string): string[] {
  const lines = text.replace(/^\uFEFF/, '').split('\n').map(cmp)
  while (lines.length && lines[0] === '') lines.shift()
  while (lines.length && lines[lines.length - 1] === '') lines.pop()
  return lines
}

/**
 * If the lines starting at `start` are exactly the lines of one of the
 * shipped texts (trailing whitespace and line endings aside), return the
 * index of the last line of that match. The longest match wins.
 */
function matchShipped(lines: string[], start: number, shipped: string[][]): number {
  let best = -1
  for (const want of shipped) {
    if (start + want.length > lines.length) continue
    let ok = true
    for (let k = 0; k < want.length; k++) {
      if (cmp(lines[start + k]) !== want[k]) { ok = false; break }
    }
    if (ok && start + want.length - 1 > best) best = start + want.length - 1
  }
  return best
}

const isBoundary = (line: string) => /^ {0,3}#{1,2}(?:[ \t]|$)/.test(bare(line))

export function upsertInstructionSection(
  content: string | null,
  opts: InstructionSectionOptions,
): InstructionSectionResult {
  const fresh = opts.section.replace(/^\s+/, '')
  if (content === null) {
    return { content: opts.title ? `${opts.title}\n\n${fresh}` : fresh, status: 'created', keptSections: 0 }
  }

  const bom = content.startsWith(BOM)
  const body = bom ? content.slice(1) : content
  const crlf = body.includes('\r\n')
  const eol = crlf ? '\r\n' : '\n'
  const sectionLines = fresh.replace(/\n$/, '').split('\n').map(l => crlf ? l + '\r' : l)

  const lines = body.split('\n')
  const { hidden, openAtEnd } = hiddenLines(lines)
  const heading = opts.heading.trim()
  const shipped = opts.shipped.map(comparable).filter(s => s.length > 0)

  type Found = { start: number; end: number; kind: 'current' | 'shipped' | 'user' }
  const found: Found[] = []
  for (let i = 0; i < lines.length; i++) {
    if (hidden[i] || norm(lines[i]) !== heading || !/^ {0,3}#/.test(lines[i])) continue
    // A current section: its marker on a line of its own, outside any fence
    // or comment block, before the next level-1/2 heading.
    let current = false
    for (let j = i + 1; j < lines.length; j++) {
      if (hidden[j]) continue
      if (isBoundary(lines[j])) break
      if (norm(lines[j]) === opts.marker.trim()) { current = true; break }
    }
    if (current) { found.push({ start: i, end: i, kind: 'current' }); continue }
    const end = matchShipped(lines, i, shipped)
    found.push(end >= 0 ? { start: i, end, kind: 'shipped' } : { start: i, end: i, kind: 'user' })
  }

  const keptSections = found.filter(f => f.kind === 'user').length
  const shippedFound = found.filter(f => f.kind === 'shipped')
  const hasCurrent = found.some(f => f.kind === 'current')

  if (shippedFound.length === 0) {
    if (hasCurrent) return { content, status: 'already', keptSections }
    // Appending keeps the file's own trailing whitespace (re-audit low e). A
    // file that ends inside an open code fence or HTML comment gets that block
    // closed first, or the new section would be hidden in it and every later
    // run would append another (re-audit R1). Closing a block at the end of the
    // file does not change how anything before it renders: an unclosed block
    // already runs to the end of the document.
    if (openAtEnd?.kind === 'unsure') {
      return {
        content, status: 'skipped', keptSections,
        skipReason: 'the file ends inside a code block that PLUR cannot tell is closed — close it and run again',
      }
    }
    let out = body
    if (out !== '' && !out.endsWith('\n')) out += eol
    if (openAtEnd) out += openAtEnd.close + eol
    if (out !== '' && !/\n[ \t]*\r?\n$/.test(out)) out += eol
    // Section lines already carry their CR in a CRLF file, so they join with '\n'.
    out += sectionLines.join('\n') + '\n'
    return {
      content: (bom ? BOM : '') + out, status: 'added', keptSections,
      ...(openAtEnd ? { closedOpenBlock: openAtEnd.kind } : {}),
    }
  }

  // Rebuild: the first shipped section becomes the new one (unless a current
  // section is already present); further shipped copies are removed. The lines
  // between them are copied unchanged.
  const out: string[] = []
  let pos = 0
  let placed = hasCurrent
  const isBlank = (l: string) => norm(l) === ''
  for (const f of shippedFound) {
    const before = lines.slice(pos, f.start)
    let after = f.end + 1
    while (after < lines.length && isBlank(lines[after]) && !(after === lines.length - 1 && lines[after] === '')) after++
    const restEmpty = after >= lines.length || (after === lines.length - 1 && lines[after] === '')
    if (!placed) {
      out.push(...before, ...sectionLines)
      placed = true
      if (!restEmpty) out.push(crlf ? '\r' : '')
    } else {
      // Removing a stale copy: keep one blank line between what came before and what follows.
      while (before.length && isBlank(before[before.length - 1])) before.pop()
      out.push(...before)
      if (!restEmpty && before.length) out.push(crlf ? '\r' : '')
    }
    pos = after
  }
  out.push(...lines.slice(pos))
  let text = out.join('\n')
  if (!text.endsWith('\n')) text += text.endsWith('\r') ? '\n' : eol
  return { content: (bom ? BOM : '') + text, status: 'upgraded', keptSections }
}

/** True when `content` is exactly one of the shipped texts, trailing whitespace and line endings aside. */
export function isShippedText(content: string, shipped: readonly string[]): boolean {
  const got = comparable(content).join('\n')
  return shipped.some(s => comparable(s).join('\n') === got)
}

/** True when `marker` stands on a line of its own outside any fence or comment block. */
export function hasStandaloneMarker(content: string, marker: string): boolean {
  const lines = content.replace(/^\uFEFF/, '').split('\n')
  const { hidden } = hiddenLines(lines)
  return lines.some((l, i) => !hidden[i] && norm(l) === marker.trim())
}

/** `name.plur-backup-YYYYMMDDTHHMMSSZ` next to the file. */
export function backupPath(path: string, now: Date = new Date()): string {
  const stamp = now.toISOString().replace(/[-:]/g, '').replace(/\.\d+Z$/, 'Z')
  let candidate = `${path}.plur-backup-${stamp}`
  for (let n = 2; existsSync(candidate); n++) candidate = `${path}.plur-backup-${stamp}-${n}`
  return candidate
}

/** Best-effort fsync of a file or directory; some platforms cannot fsync a directory. */
function syncPath(path: string, flags: string): void {
  let fd: number | undefined
  try {
    fd = openSync(path, flags)
    fsyncSync(fd)
  } catch { /* not supported here (e.g. a directory on Windows) */ } finally {
    if (fd !== undefined) try { closeSync(fd) } catch { /* ignore */ }
  }
}

/**
 * Copy an existing file to a timestamped backup beside it; returns the backup
 * path. With `once`, an existing backup holding the same content is reused,
 * so re-running on an unchanged file does not pile up copies (re-audit low c).
 * The copy is created exclusively (COPYFILE_EXCL, retrying with a new name),
 * so two writers can never share or overwrite one backup (third re-audit N2),
 * and it is flushed to disk.
 */
export function backupFile(path: string, opts: { once?: boolean } = {}): string | null {
  if (!existsSync(path)) return null
  if (opts.once) {
    const current = readFileSync(path)
    const dir = dirname(path)
    const prefix = `${basename(path)}.plur-backup-`
    for (const f of readdirSync(dir).filter(n => n.startsWith(prefix)).sort()) {
      try { if (readFileSync(join(dir, f)).equals(current)) return join(dir, f) } catch { /* unreadable: ignore */ }
    }
  }
  for (let attempt = 0; ; attempt++) {
    const dest = backupPath(path)
    try {
      copyFileSync(path, dest, constants.COPYFILE_EXCL)
      syncPath(dest, 'r')
      return dest
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'EEXIST' || attempt >= 20) throw err
    }
  }
}

/** A write PLUR declined to make; the message says why. Callers report it and carry on. */
export class InstructionWriteRefused extends Error {
  readonly code = 'PLUR_REFUSED'
  constructor(message: string) {
    super(message)
    this.name = 'InstructionWriteRefused'
  }
}

/**
 * Write `content` to `path`, first copying any existing file to a timestamped
 * backup beside it. Returns the backup path, or null when the file is new.
 *
 * `expected` is the text the caller read and built `content` from (null:
 * the caller saw no file). If the file no longer holds it — the user saved
 * in between — nothing is written and InstructionWriteRefused is thrown, so
 * the user's edit is never overwritten (third re-audit N2). The same check
 * runs again just before the new content is swapped in.
 *
 * The new content goes to a temporary file in the same directory, flushed to
 * disk, then renamed over the target, so the target is never truncated or half
 * written: a failure partway leaves the user's file exactly as it was (second
 * re-audit H1). The temporary file is removed on failure, and so is the
 * backup, but only when the target still holds the original bytes. Permission
 * bits are kept, and owner and group too where the process may set them.
 *
 * What the file is, is kept (third re-audit N2): a symlink is written through
 * to its target; a symlink to a missing file is refused rather than replaced
 * by a regular file; a file with several hard links is written in place
 * (after the backup) so every name still sees the same text. A file that is
 * not writable is refused before anything is copied (re-audit low d).
 */
export function writeWithBackup(path: string, content: string, expected?: string | Buffer | null): string | null {
  const asBuffer = (v: string | Buffer) => (typeof v === 'string' ? Buffer.from(v) : v)
  let link: ReturnType<typeof lstatSync> | null = null
  try { link = lstatSync(path) } catch { link = null }
  const exists = existsSync(path)

  if (link?.isSymbolicLink() && !exists) {
    throw new InstructionWriteRefused(`it is a symlink to ${readlinkSync(path)}, which is missing — PLUR will not replace the link`)
  }
  if (!exists) {
    if (expected != null) throw new InstructionWriteRefused('it was removed while PLUR was updating it — run again')
    try {
      writeFileSync(path, content, { flag: 'wx' })
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'EEXIST') {
        throw new InstructionWriteRefused('it was created while PLUR was updating it — run again')
      }
      throw err
    }
    return null
  }

  const target = realpathSync(path)
  accessSync(target, constants.W_OK)
  const original = readFileSync(target)
  const st = statSync(target)
  if (expected != null && !original.equals(asBuffer(expected))) {
    throw new InstructionWriteRefused('it changed after PLUR read it — run again')
  }
  const backup = backupFile(target)
  const dropBackupIfUnchanged = () => {
    if (!backup) return
    let unchanged = false
    try { unchanged = readFileSync(target).equals(original) } catch { /* unreadable: keep the backup */ }
    if (unchanged) { try { unlinkSync(backup) } catch { /* report the original error, not this */ } }
  }

  if (st.nlink > 1) {
    // Several names share this file: writing in place keeps them shared. The
    // backup taken above is what protects the text if this write fails.
    try {
      writeFileSync(target, content)
      syncPath(target, 'r+')
    } catch (err) {
      dropBackupIfUnchanged()
      throw err
    }
    return backup
  }

  const tmp = join(dirname(target), `.${basename(target)}.plur-tmp-${process.pid}-${randomBytes(4).toString('hex')}`)
  try {
    writeFileSync(tmp, content, { flag: 'wx', mode: st.mode & 0o7777 })
    chmodSync(tmp, st.mode & 0o7777)
    try { chownSync(tmp, st.uid, st.gid) } catch { /* not permitted for this process: keep ours */ }
    syncPath(tmp, 'r+')
    if (!readFileSync(target).equals(original)) {
      throw new InstructionWriteRefused('it changed while PLUR was updating it — run again')
    }
    renameSync(tmp, target)
  } catch (err) {
    try { unlinkSync(tmp) } catch { /* never created, or already gone */ }
    dropBackupIfUnchanged()
    if (err instanceof InstructionWriteRefused && backup) { try { unlinkSync(backup) } catch { /* ignore */ } }
    throw err
  }
  syncPath(dirname(target), 'r')
  return backup
}
